name = input("Enter your name: ")
age = int(input("Enter your age: "))
favorite_color = input("Enter your favorite color: ")
favorite_movie = input("Enter your favorite movie: ")
mobile_number = input("Enter your 11-digit mobile number: ")
motto_in_life = input("Enter your motto in life: ")